/**
 * Renders the Jetzy demo as a shareable MP4 via Shotstack.
 *
 * Architecture: real ElevenLabs voice conversation between Aria and
 * Marco plays sequentially as the AUDIO track. The VIDEO track shows
 * the matching location for what's being said at that moment — viewer
 * is "transported" to each place as the dialog flows.
 *
 * Audio files are pre-generated by scripts/generate-demo-audio.mjs
 * and live in /public/demo-audio/. The manifest there has each line's
 * exact duration measured by ffprobe, so the timeline syncs perfectly.
 */

const SHOTSTACK_URL = 'https://api.shotstack.io/edit/stage/render';

// Scene → matching landscape video URL (Pexels older-format URLs that
// Shotstack can fetch — verified)
const SCENE_VIDEOS = {
  kilimanjaro:    'https://videos.pexels.com/video-files/35646306/15106052_1920_1080_30fps.mp4',
  buenos_aires:   'https://videos.pexels.com/video-files/856975/856975-hd_1920_1080_25fps.mp4',
  don_julio:      'https://videos.pexels.com/video-files/7174763/7174763-hd_1920_1080_30fps.mp4',
  el_chalten:     'https://videos.pexels.com/video-files/2611250/2611250-hd_1920_1080_30fps.mp4',
  fitz_roy:       'https://videos.pexels.com/video-files/2421545/2421545-hd_1920_1080_30fps.mp4',
  perito_moreno:  'https://videos.pexels.com/video-files/8318417/8318417-hd_1920_1080_25fps.mp4',
  mendoza:        'https://videos.pexels.com/video-files/4763824/4763824-hd_1920_1080_24fps.mp4',
  wine_pour:      'https://videos.pexels.com/video-files/8849303/8849303-hd_1920_1080_24fps.mp4',
};

// Mission card durations (no audio, just visual)
const MISSION_OPEN  = { title: 'Plan a trip in 90 seconds', subtitle: 'No tabs. No spreadsheets. Just answers.', duration: 3 };
const MISSION_CLOSE = { title: 'This is Jetzy',             subtitle: 'Your travel companion. Plan it, book it, done.', duration: 4 };

const PAUSE_BETWEEN_LINES = 0.2; // small breath between speakers

function missionClip(start, scene) {
  return {
    asset: {
      type: 'html',
      html: `<div style="width:1280px;height:720px;background:#1B2B4B;display:flex;flex-direction:column;justify-content:center;align-items:center;font-family:'Playfair Display',Georgia,serif;">
        <div style="font-size:14px;letter-spacing:6px;color:#C9A84C;margin-bottom:24px;font-weight:bold;">JETZY</div>
        <div style="font-size:64px;color:white;font-weight:700;text-align:center;margin:0 80px;line-height:1.1;">${scene.title}</div>
        <div style="font-size:24px;color:rgba(255,255,255,0.7);text-align:center;margin:30px 80px 0;font-family:Inter,system-ui,sans-serif;font-weight:400;">${scene.subtitle}</div>
      </div>`,
      width: 1280, height: 720,
    },
    start,
    length: scene.duration,
    transition: { in: 'fade', out: 'fade' },
  };
}

function captionClip(start, length, speaker, text) {
  const isUser = speaker === 'marco';
  const bg = isUser ? 'rgba(201,168,76,0.92)' : 'rgba(0,0,0,0.78)';
  const accent = isUser ? '#FFFFFF' : '#C9A84C';
  const label = isUser ? 'MARCO' : 'ARIA';
  const safe = text.replace(/"/g, '&quot;');
  return {
    asset: {
      type: 'html',
      html: `<div style="width:1100px;display:flex;justify-content:center;"><div style="background:${bg};backdrop-filter:blur(10px);padding:18px 28px;border-radius:18px;border:1px solid rgba(201,168,76,0.3);max-width:1100px;"><div style="color:${accent};font-size:11px;letter-spacing:3px;font-family:Inter,system-ui,sans-serif;font-weight:700;margin-bottom:6px;">${label}</div><div style="color:white;font-size:26px;font-family:Inter,system-ui,sans-serif;font-weight:500;line-height:1.4;">${safe}</div></div></div>`,
      width: 1100, height: 140,
    },
    start: start + 0.15,
    length: length - 0.2,
    position: 'bottom',
    offset: { y: -0.05 },
    transition: { in: 'fade', out: 'fade' },
  };
}

async function loadManifest(req) {
  // We're inside a Vercel function — the public folder is served at the
  // root of our deployment. Fetch the manifest from our own host.
  const host = req.headers.host;
  const proto = host.includes('localhost') ? 'http' : 'https';
  const url = `${proto}://${host}/demo-audio/manifest.json`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`Manifest fetch failed: ${r.status}`);
  return await r.json();
}

function buildTimeline(host, manifest) {
  const proto = host.includes('localhost') ? 'http' : 'https';
  const audioBase = `${proto}://${host}`;

  const videoTrack = [];
  const audioTrack = [];
  const captionTrack = [];

  let t = 0;

  // Opening mission card (no audio)
  videoTrack.push(missionClip(t, MISSION_OPEN));
  t += MISSION_OPEN.duration;

  // Each spoken line: video clip matched to the scene + audio + caption
  // Group consecutive lines that share the same scene under one continuous
  // video clip (so the background doesn't restart mid-conversation)
  let runStart = t;
  let runScene = null;

  for (let i = 0; i < manifest.length; i++) {
    const line = manifest[i];
    const next = manifest[i + 1];
    const lineLen = line.duration + PAUSE_BETWEEN_LINES;

    // Add audio + caption for this line
    audioTrack.push({
      asset: { type: 'audio', src: `${audioBase}${line.file}`, volume: 1 },
      start: t,
      length: line.duration,
    });
    captionTrack.push(captionClip(t, lineLen, line.speaker, line.text));

    // Start a new video clip when scene changes
    if (runScene === null) runScene = line.scene;

    const sceneChangesNext = !next || next.scene !== line.scene;
    if (sceneChangesNext) {
      const runLength = (t + lineLen) - runStart;
      const videoSrc = SCENE_VIDEOS[runScene] || SCENE_VIDEOS.kilimanjaro;
      videoTrack.push({
        asset: { type: 'video', src: videoSrc, volume: 0 },
        start: runStart,
        length: runLength,
        fit: 'cover',
        transition: { in: 'fade', out: 'fade' },
      });
      runStart = t + lineLen;
      runScene = next ? next.scene : null;
    }

    t += lineLen;
  }

  // Closing mission card (no audio)
  videoTrack.push(missionClip(t, MISSION_CLOSE));
  t += MISSION_CLOSE.duration;

  return {
    timeline: {
      background: '#000000',
      tracks: [
        { clips: captionTrack }, // top — captions
        { clips: audioTrack },   // audio dialog
        { clips: videoTrack },   // bottom — backgrounds
      ],
    },
    output: {
      format: 'mp4',
      resolution: 'hd', // 1280x720
      fps: 30,
    },
  };
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const apiKey = process.env.SHOTSTACK_SANDBOX_KEY;
  if (!apiKey) return res.status(500).json({ error: 'SHOTSTACK_SANDBOX_KEY not set' });

  try {
    const manifest = await loadManifest(req);
    const payload = buildTimeline(req.headers.host, manifest);

    const r = await fetch(SHOTSTACK_URL, {
      method: 'POST',
      headers: { 'x-api-key': apiKey, 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    const data = await r.json();
    if (!r.ok || !data?.success) {
      return res.status(500).json({ error: 'Shotstack render failed', detail: data });
    }

    const totalDuration = manifest.reduce((s, m) => s + m.duration + PAUSE_BETWEEN_LINES, 0)
                        + MISSION_OPEN.duration + MISSION_CLOSE.duration;

    return res.status(200).json({
      id: data.response?.id,
      message: data.response?.message,
      poll: `/api/render-status?id=${data.response?.id}`,
      estimatedDurationSec: Number(totalDuration.toFixed(1)),
      lines: manifest.length,
    });
  } catch (e) {
    return res.status(500).json({ error: 'Render error', detail: e.message });
  }
}
